### ISSUE TITLE
Can't start cuckoo web

### ISSUE THREAD

**Issue by axel36rus** [cert-ee/cuckoo3#19]
(venv) cuckoo@cuckoo-sandbox:~$ cuckoo web --host 192.168.xxx.xx --port 8080
Performing system checks...

Traceback (most recent call last):
  File "/opt/cuckoo3/venv/bin/cuckoo", line 11, in <module>
    load_entry_point('Cuckoo', 'console_scripts', 'cuckoo')()
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/cuckoo3/core/cuckoo/main.py", line 424, in web
    start_web(host, port, autoreload=autoreload)
  File "/opt/cuckoo3/web/cuckoo/web/web/startup.py", line 132, in start_web
    execute_from_command_line(args)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 111, in handle
    self.run(**options)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 120, in run
    self.inner_run(None, **options)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/cuckoo3/web/cuckoo/web/web/urls.py", line 24, in <module>
    path("api/", include("cuckoo.web.uiapi.urls")),
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/cuckoo3/web/cuckoo/web/uiapi/urls.py", line 7, in <module>
    path("analyses/", include("uiapi.analyses.urls")),
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/cuckoo3/web/cuckoo/web/uiapi/analyses/urls.py", line 7, in <module>
    from . import views
  File "/opt/cuckoo3/web/cuckoo/web/uiapi/analyses/views.py", line 118
    )
    ^
SyntaxError: invalid syntax

views.py line 115-118:

def get(self, request, analysis_id):
        if not cfg(
            "web.yaml", "web", "downloads", "submitted_file", subpkg="web"
        )

**Comment by NicolasFR** [comment]
In the file /opt/cuckoo3/web/cuckoo/web/uiapi/analyses/views.py you can change 
```python
def get(self, request, analysis_id):
if not cfg(
"web.yaml", "web", "downloads", "submitted_file", subpkg="web"
)
```
By
```python
    def get(self, request, analysis_id):
        if not cfg(
            "web.yaml", "elasticsearch", "web_search", "enabled",
            subpkg="web"
        ):
```
