### ISSUE TITLE
Error when creating the Cuckoo CWD

### ISSUE THREAD

**Issue by trangnt2304** [cert-ee/cuckoo3#29]
I follow the insstruction and type
`cuckoo createcwd`
but the terminal show this error

root@sandbox:/opt/cuckoo3# cuckoo createcwd
^[[FTraceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.7.3 (/usr/lib/python3/dist-packages), Requirement.parse('python-dateutil<3.0.0,>=2.8.2'), {'pymisp'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cuckoo", line 33, in <module>
    sys.exit(load_entry_point('Cuckoo', 'console_scripts', 'cuckoo')())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/cuckoo3/core/cuckoo/main.py", line 123, in create_cwd
    cuckoocwd.set(cwd_path)
  File "/opt/cuckoo3/common/cuckoo/common/storage.py", line 243, in set
    outdated = self.discover_outdated_versions()
  File "/opt/cuckoo3/common/cuckoo/common/storage.py", line 187, in discover_outdated_versions
    from pkg_resources import parse_version
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.7.3 (/usr/lib/python3/dist-packages), Requirement.parse('python-dateutil<3.0.0,>=2.8.2'), {'pymisp'})

Can someone help me please :(

**Comment by Cryss76** [comment]
The root of your problems seems to be that you are running cuckoo as root, which is a bad idea in general.

You also aren't using a venv and instead installed cuckoo globally which will easily cause versions conflicts.
(in this case I'm guessing the wrong setuptools version is beeing used)

Create cuckoo user the create a venv and install cuckoo in context of the user you created.

If you need root for cuckoo routes use cuckoo rooter for dealing with it.

**Comment by rkivistik** [comment]
@Cryss76 answer is correct.
It is recommended to create a venv and cuckoo user.
Closing the issue.
If the problem persists, please open a new issue.
