### ISSUE TITLE
The 'urllib3<2,>=1.21.1' distribution was not found and is required by elasticsearch

### ISSUE THREAD

**Issue by Rayal** [cert-ee/cuckoo3#39]
After running `./install.sh` from cuckoo home directory (using venv), it installs all the requirements.
After that, when I run `cuckoo createcwd` and I get the error message

```
(venv) cuckoo@cuckoo3:/opt/cuckoo3$ cuckoo createcwd
Traceback (most recent call last):
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 2.0.2 (/opt/cuckoo3/venv/lib/python3.8/site-packages), Requirement.parse('urllib3<2,>=1.21.1'), {'elasticsearch'})
```

**Comment by Cryss76** [comment]
Pls describe next time the system you're using and your steps before executing `./install.sh`. Also posting the complete error and output of `./install.sh` would have been helpful.

Nevertheless, I was able to reproduce your problem and fix it on an lxc-container. (I used this ugly script I'm working on: https://github.com/Cryss76/Cuckoo3_setup_helper/blob/main/setupCuckoo3lxc.sh)

After creating the container, I ssh into it and created the same folder you're using for your venv with `sudo mkdir /opt/cuckoo3`.
Then I changed the ownership of the folder with `sudo chown cuckoo:cuckoo /opt/cuckoo3`.
With `virtualenv /opt/cuckoo3/venv`, I finally had the same env you seem to use.
I preceeded with executing `./install.sh`. This yield the following error, which you seemed to have missed:
```bash
ERROR: elasticsearch 7.17.9 has requirement urllib3<2,>=1.21.1, but you'll have urllib3 2.0.2 which is incompatible.
```
After the installation process was finished, executing `cuckoo createcwd` reproduced the exception you posted and also another one:
```bash
(venv) cuckoo@cuckoo3:~/cuckoo3$ cuckoo createcwd
Traceback (most recent call last):
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 2.0.2 (/opt/cuckoo3/venv/lib/python3.8/site-packages), Requirement.parse('urllib3<2,>=1.21.1'), {'elasticsearch'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cuckoo3/venv/bin/cuckoo", line 33, in <module>
    sys.exit(load_entry_point('Cuckoo', 'console_scripts', 'cuckoo')())
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cuckoo/cuckoo3/core/cuckoo/main.py", line 123, in create_cwd
    cuckoocwd.set(cwd_path)
  File "/home/cuckoo/cuckoo3/common/cuckoo/common/storage.py", line 243, in set
    outdated = self.discover_outdated_versions()
  File "/home/cuckoo/cuckoo3/common/cuckoo/common/storage.py", line 187, in discover_outdated_versions
    from pkg_resources import parse_version
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/cuckoo3/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3<2,>=1.21.1' distribution was not found and is required by elasticsearch
```

My first guess here was to update pip, which also fixed the issue:
```bash
pip install -U pip
./install.sh                                        # No error this time
cuckoo createcwd --regen-configs
```

**Comment by Cryss76** [comment]
@Rayal did this solve your problem? If so, pls close the issue.

**Comment by Cryss76** [comment]
@amadisson  pls close as there was no reply of @Rayal
